file:C:/INSTALLED/Git/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/INSTALLED/Git/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/INSTALLED/Git/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/INSTALLED/Git/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/INSTALLED/Git/Git/etc/gitconfig	filter.lfs.required=true
file:C:/INSTALLED/Git/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/INSTALLED/Git/Git/etc/gitconfig	http.sslcainfo=C:/INSTALLED/Git/Git/mingw64/etc/ssl/certs/ca-bundle.crt
file:C:/INSTALLED/Git/Git/etc/gitconfig	core.autocrlf=true
file:C:/INSTALLED/Git/Git/etc/gitconfig	core.fscache=true
file:C:/INSTALLED/Git/Git/etc/gitconfig	core.symlinks=true
file:C:/INSTALLED/Git/Git/etc/gitconfig	core.fsmonitor=true
file:C:/INSTALLED/Git/Git/etc/gitconfig	pull.rebase=false
file:C:/INSTALLED/Git/Git/etc/gitconfig	credential.helper=manager
file:C:/INSTALLED/Git/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/INSTALLED/Git/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/RSU5/.gitconfig	user.name=shristisinha266
file:C:/Users/RSU5/.gitconfig	user.email=shristisinha31aug2003@gmail.com
file:C:/Users/RSU5/.gitconfig	color.ui=true
file:C:/Users/RSU5/.gitconfig	core.editor=emacs
